### PR TITLE
Implement custom playlists

### PR DESCRIPTION
**Pull request by greg321321**
This is just an early preview draft of the functionality. You should be able to take the feature for a spin and provide me some feedback. Ticket #590 has screenshots of expected functionality. I still need to align the code to existing patterns in the project, disable debugging, remove unimplemented functions, update documentation, etc.

### CODE REVIEW

**Comment by bbilly1** [comment]
It's worth looking into how I implemented the current playlist functionality and integrate as much of that as possible. 

If you look how I implemented that, you'll see the video document in ES has a playlist array, with a list of playlist IDs where this video can be found. Then the playlist document in ES has the playlist_entries, that only contains the minimum needed to basically build the playlist navigation and not the complete video metadata. This way you avoid duplication as much as possible and you can have separation of concern as much as possible.

So to implement custom playlists you don't need a separate index in ES for that, also you wouldn't want to duplicate the complete video metadata to playlist_entries, that is going to balloon your index as a video can be in multiple playlists, theoretically even the same video can be multiple times in the same playlist. Then you'll also have to consider other functionality of this application like reindex video metadata...

What you need is a way to differentiate between youtube and local playlist, you could do that by adding a bool flag to the existing playlists, like `is_local`, then if that is true, this playlist has additional functionality like this but needs to be excluded from the reindex task, if that is false, this playlist is a regular youtube playlist.

With that you can reuse a lot of the existing functionality and don't end up duplicating everything.

I hope that makes sense.

**Comment by greg321321** [comment]
Your approach makes sense, I'll take a look.

**Comment by bbilly1** [comment]
feel free to reopen with the new approach.

**Comment by greg321321** [comment]
ok

**Pull request closed without merging**
