### PR TITLE
change redis persistence from 1 hour (default) to 1 minute

### PR DESCRIPTION
**Pull request by contributor**
Update docker-compose.yaml sample file to configure redis persistence frequency

Fix https://github.com/tubearchivist/tubearchivist/issues/457

### CODE REVIEW

**Comment by bbilly1** [comment]
Did some research on that, I hear you and I see I was under the wrong assumption that redis triggers a write automatically on shutdown.

Ultimately in the long run, we will want to move away from redis persistence, that has been more trouble that it's worth: #517. But that's unclear on what time frame that will happen.

Ultimately changing the compose file is tricky and manual on user side, unclear how many that will actually do. Also whatever you set the schedule to, 1min might not be fast enough, e.g. save config and restart immediately wouldn't do it, plus that will create a lot of unnecessary writes. 

Alternatively how about we call [BGSAVE](https://redis.io/commands/bgsave/) application internally whenever we write a persistent value to redis, basically if not expire [here](https://github.com/tubearchivist/tubearchivist/blob/master/tubearchivist/home/src/ta/ta_redis.py#L38-L55). So it's tied to the application logic, only called when needed, folks don't need to update their compose files, and easy enough to revert once we can avoid persistence altogether in the future. 

Thoughts?

**Comment by bbilly1** [comment]
OK, we are not the first ones to get confused here: https://github.com/redis-stack/redis-stack/issues/371

That's apparently an desired difference with the main redis image, ans also with our previous RedisJSON image.

**Comment by contributor** [comment]
BGSAVE sounds good. But not sure if this worth efforts to call it all places from the app code if the plan to get rid of redis. And for SIGTERM, BGSAVE will only work if redis containter stops after TA container.

Still I believe additional line in compose is easy work-arround for time being, to prevent new users (like me) to give up on TA. I almost did that after spending many hours to find out why settings are never saved. I'm glad I didn't give up - the app looks fantastic (I'm mainly interested in comments/subtitle indexing feature)

**Comment by contributor** [comment]
Good news. What about queue and task? Don't they need bgsave?

**Comment by bbilly1** [comment]
queue and tasks in redis are adhoc anyways. they are usually built from persistent ES and loaded into redis for the duration of the task to take from. but they don't survive a container restart anyways and can always be recreated from ES again.

**Pull request closed without merging**
