### PR TITLE
adds api/channels/<channel>/about/

### LINKED ISSUE #725: [Frontend Migration]: Add API endpoint /api/channel/{channel-id}/about/
### Domain

Backend

## Is your feature request related to a problem? Please describe.
Data for the page `/channel/{channel-id}/about` is missing in the api endpoints.

## Describe the solution you'd like
The Api endpoint `/api/channel/{channel-id}/about/` has been implemented.

## Additional context
`/api/channel/{channel-id}/about/` ( POST )

POST body:
 ```Json
{
  "download_format": "",
  "autodelete_days": 0,
  "index_playlists": false,
  "integrate_sponsorblock": false
}
```

Possibly implemented in a module way as described in https://github.com/tubearchivist/tubearchivist/issues/721

### PR DESCRIPTION
**Pull request by kralverde**
closes #725

### CODE REVIEW

**Comment by kralverde** [comment]
Oh shoot I forgot to add the POST

**Comment by bbilly1** [comment]
Thanks for sticking with it! Highly appreciate it. I'm messing around with https://github.com/tubearchivist/tubearchivist/issues/721, this is going to move everything around. Please give me some time to wrap this up first.

**Comment by kralverde** [comment]
Sounds good, I'll wait 'till then.

**Comment by bbilly1** [comment]
OK, if you are still up for it, I've merged my stuff, please rebase. 

Then I hope you find your way around in the new structure and layout.

Let me know if you are good to continue.

**Comment by kralverde** [comment]
i'll probably just close this PR and make another one

**Comment by kralverde** [comment]
closed in favor of https://github.com/tubearchivist/tubearchivist/pull/783

**Pull request closed without merging**
