### PR TITLE
Split the settings page

### PR DESCRIPTION
**Pull request by anonamouslyginger**
As mentioned in #415 one of the outstanding tasks is to 'Split up settings page into separate sub pages'.

Here is my first attempt at that.
Assuming that I have captured everything I have created 4 views:
1. User Settings (the 'main' setting page at `/settings/`)
2. Application Settings (at `/settings/application/`)
3. Scheduling Settings (at `/settings/scheduling/`)
4. Actions (at `/settings/actions/`)

I have explicitly tried to not also solve the removal of POST forms to keep this PR well contained and 'simple'.
Please let me know if it matches your expectations @bbilly1.

See below the screenshots:
image
image
image
image

### CODE REVIEW

**Comment by anonamouslyginger** [comment]
Excellent!

The idea of a dashboard sounds great! I will make the users setting its own page and I can see three possible interim solutions for `/settings/`:
1. Temporary redirect to `/settings/users/` and we can later replace the redirect with a page containing the dashboard
2. A page that has a 'coming soon' banner or similar, letting users know that a dashboard will be added later
3. A page that just has the sub menu for now

I can see benefits for each solution

**Comment by bbilly1** [comment]
I'd say some sort of coming soon message would be fine for now. Then I'll try to at least implement some basics for the dashboard there, something to extend on but to have something there before it goes out in a release.

**Comment by anonamouslyginger** [comment]
Alright, I have added the dashboard page, see the screenshot below.

This page is now shown on `/settings/` and the user settings are on `/settings/user/`.

image

And on mobile:
image

**Comment by bbilly1** [comment]
That's it, I think you got it. I've been adding some API routes for stats to use in the dashboard. I can do that in a second step. I'd say double check all then this should be good.

**Comment by anonamouslyginger** [comment]
I've been through and set each setting and I'm happy that everything is working in it's new location now.
I broke the display of snapshots but that's fixed now.

I will mark the review as ready for review, thanks for the help @bbilly1!

**Comment by bbilly1** [comment]
Very nice! thanks a lot for implementing this. I'll try to implement some statistics on the dashboard there next.

And obviously, please keep going! You seem to have a good handle on things. There are more small or big improvements waiting, just for you. :-)

**Pull request merged**
