### PR TITLE
Document how to update in the readme

### PR DESCRIPTION
**Pull request by bakkot**
I went to the `Update` section of the readme expecting to find a description of how to update, but it wasn't there. Found it in the discord instead and figured I'd put it here for any future readers.

If there's a different update process, happy to change the readme so it describes that instead.

### CODE REVIEW

**Comment by bbilly1** [comment]
Ultimately that depends on what platform you are using. I think around 50% of TA users use regular docker compose. Then the rest use any of the myriad of other ways that you can run a docker container and they have their own ways how to update.

But ultimately, there aren't any special steps (well besides reading the release notes), you can update TA the same way as you update any docker container, pull and rebuild, that's not specific to TA but that will also be different between platforms.

So I'd say to keep the instructions in the readme generic, so they apply to all/most, then we still have the dedicated instructions in the docs. Maybe that would fit there better?

**Comment by bakkot** [comment]
> But ultimately, there aren't any special steps (well besides reading the release notes), you can update TA the same way as you update any docker container, pull and rebuild, that's not specific to TA but that will also be different between platforms.

I can change it to say "for example", if that would help? I think anyone using something other than the basic setup is probably familiar with how to do updates on their platform. But I think it's worth having instructions for the basic setup in the readme. For some people - for example, me - this is the only docker-compose project they're using. I think it's worth having a sentence giving instructions for such people in the readme.

**Comment by bbilly1** [comment]
Sounds good, maybe change it so something like *depending on your platform* and *for example*. Also there is no need for `down`, just `pull` and `up` should do it.

**Comment by bakkot** [comment]
Done.

**Pull request merged**
