### PR TITLE
Healthcheck endpoint

### PR DESCRIPTION
**Pull request by ajgon**
This PR adds simple `/health` endpoint which is usable in docker swarm or kubernetes environments, which use periodical healthchecks of the container.

### CODE REVIEW

**Comment by bbilly1** [comment]
hmm, we already have a [`/api/ping/`](https://github.com/tubearchivist/tubearchivist/blob/master/tubearchivist/api/views.py#L628-L641) view for such occasions. Maybe that would do aswell?

**Comment by lamusmaser** [comment]
Clusters tend to default to a `/healthcheck` endpoint that responds with a simple `OK`, unless @ajgon notes otherwise. Haven't had to build one for a long while.

**Comment by ajgon** [comment]
I'm fine with any name for the endpoint. I can rename it to `/healthcheck` as well :)

@bbilly1 - the problem with `/api/ping/` is, that is hidden behind authorization - and returns 403. Usually healthcheck endpoints expect one of the `2xx` (preferably `200`) statuses.

**Comment by lamusmaser** [comment]
I'm good with `/health` or `/healthcheck`.

Since this project has dependencies, we may also need to show their status, unless you aren't worried about their up status since we can assume it from TA being online.

**Comment by bbilly1** [comment]
Nice, sounds good. Please also make a mention in the docs, maybe with a docker-compose example similar to:
```yml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 60s
```
Then this should be enough for other platform who have their own health check functionality or such to build their own.

**Pull request merged**
