### PR TITLE
Add API endpoint for searching 

### PR DESCRIPTION
**Pull request by PrivateGER**
Created for #290  

This adds the /api/search?query=term endpoint to facilitate API-based search. I also changed the frontend to use this new endpoint.

### CODE REVIEW

**Comment by PrivateGER** [comment]
The CI linter thingy seems to not like my formatting, even though it passes all linters just fine locally. No idea what that's about.

**Comment by bbilly1** [comment]
Excellent work, thank you for working on that! 

To make the linter happy, you can use the `deploy.sh validate` script, that runs all the same linter as the action does, so you get immediate and exact feedback: https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#code-formatting-and-linting. 

You did the work so you should get the honors: You can remove the old method from the *api_calls.py* module:
https://github.com/tubearchivist/tubearchivist/blob/13018192f327f18e17ac1cf7c1d05afc6a6c76f9/tubearchivist/home/src/frontend/api_calls.py#L289-L294

One more done, only 20 left to go. :-)

I've added a few more comments in the code.

**Comment by bbilly1** [comment]
Were you able to look into this? So we can wrap this up before the next release.

Otherwise, if you prefere, I can also push the changes to your PR.

**Comment by PrivateGER** [comment]
Was a bit busy recently, this should solve your comments.

**Pull request merged**
