### PR TITLE
Update TaskAPIView with GET - #257 PR

### PR DESCRIPTION
**Pull request by lamusmaser**
Initial commit to determine the GET response for TaskAPIView which should show if the "rescan" or "download" tasks are currently running. This is based on if the Lock is currently owned - may need to modify further if determined inadequate for task checking.

### CODE REVIEW

**Comment by lamusmaser** [comment]
This is associated with #257 and will close when merged.

**Comment by bbilly1** [comment]
Thanks for getting to work on that. The method `get_lock` of the `RedisArchivist` class will return a new lock instance every time it's called, so you won't be able to run `owned()` on a different instance than where the lock was initiated. I hope that makes sense, basically you can only call the `owned()` method here: https://github.com/tubearchivist/tubearchivist/blob/bb0f3dad1a02a375a306cc65b1689de92b6fc8e8/tubearchivist/home/tasks.py#L54 and it will be doing what you think it does. Otherwise you'll have to `acquire()` it, but that will create it if it can, so that's not what you want either. 

Basically a lock is just a key set in redis, so you can check if that key is there, that key will automatically disappear when `release()` was called on that lock, so that is a thread independent approach. 

I've pushed a commit to your PR implementing `is_locked` in the `RedisArchivist` class that is just doing that, so you can call that method in the API view.

Also note that all API views expect `self` as it's first argument and `request` as the second, like here: https://github.com/tubearchivist/tubearchivist/blob/bb0f3dad1a02a375a306cc65b1689de92b6fc8e8/tubearchivist/api/views.py#L366 you'll have to use the `staticmethod` decorator if you don't need access to `self` in that view, like here: https://github.com/tubearchivist/tubearchivist/blob/bb0f3dad1a02a375a306cc65b1689de92b6fc8e8/tubearchivist/api/views.py#L427

Otherwise Django will be unhappy because there is an unexpected amount of arguments.

**Comment by lamusmaser** [comment]
Thank you for the detailed reply. Based on my initial reading, I thought that `.get_lock()` was doing what the new `is_locked()` function is doing, so I appreciate the commit. I'll update the PR with the replacement requests.

Also noted for the `self` vs `staticmethod` decorator; I had noticed what you pointed out, but didn't make the connection that the decorator was what allowed it.

**Comment by bbilly1** [comment]
Were you able to build the image and test your changes? For linting, you can use `./deploy.sh validate` to help you out there.

**Comment by lamusmaser** [comment]
I haven't yet. I had to shut down my test server a while back, so I didn't get the time to redeploy and rebuild the image.

I will see if I can get that done sometime later this week before the PR merge.

**Comment by lamusmaser** [comment]
@bbilly1 - I have this tested and working now. Looks like we were getting a key error, but now it responds appropriately:

```
>>> r = requests.post(base_url+login_api,json=payload)
>>> headers = {"Authorization": f"Token {r.json()['token']}"}
>>> p = requests.get(base_url+ping_url,headers=headers)
>>> p.text
'{"response":"pong","user":1}'
>>> tg = requests.get(base_url+task_api,headers=headers)
>>> tg.text
'{"rescan":false,"download":false}'
>>> tp = requests.post(base_url+task_api,headers=headers,json=runtask)
>>> tp.text
'{"success":true,"task":"rescan_pending"}'
```

Testing also shows that the `POST` requests are no longer failing with Server 500 responses.

**Comment by bbilly1** [comment]
Thanks for working on that. Does it ever set to `true` for you when you have the rescan process running for example? You'll have to pass the name of the lock into the `is_locked` method. Like here: https://github.com/tubearchivist/tubearchivist/blob/bb0f3dad1a02a375a306cc65b1689de92b6fc8e8/tubearchivist/home/tasks.py#L82 this creates a lock named `downloading` so to check if that lock is set, you'll have to use the same name like `RedisArchivist().is_locked("downloading")`.

Then I saw, you also updated the README, good thinking. The return will be a bool though and not a string, so `"download": false` and not `"download": "false"`.

**Comment by lamusmaser** [comment]
README has been updated appropriately.

Had to make a minor adjustment - I was making the correct call, but wasn't using the correct key (misread which string was passed through to the end). 

```
>>> tg = requests.get(base_url+task_url,headers=headers)
>>> tg.text
'{"rescan":false,"download":false}'
>>> tp = requests.post(base_url+task_url,headers=headers,json=runtask)
>>> tp.text
'{"success":true,"task":"rescan_pending"}'
>>> tg = requests.get(base_url+task_url,headers=headers)
>>> tg.text
'{"rescan":true,"download":false}'
>>> >>> tg = requests.get(base_url+task_url,headers=headers)
>>> tg.text
'{"rescan":false,"download":false}'
```

Download was not working, so pushed another update that 1) fixed the `download` key to be `downloading` and 2) converted it to a dictionary reference loop, rather than keying each individually.

```
>>> tp = requests.post(base_url+task_url,headers=headers,json=runtask)
>>> tp.text
'{"success":true,"task":"download_pending"}'
>>> tg = requests.get(base_url+task_url,headers=headers)
>>> tg.text
'{"rescan":false,"downloading":true}'
```

At this point, the endpoint is working and responding against the two tasks; additionally, the README should be correct with the right typecast, as well.

**Comment by bbilly1** [comment]
Excellent work, this can then easily be extended with new tasks by just adding them to the list.

**Pull request merged**
