### PR TITLE
updated imagry

### PR DESCRIPTION
**Pull request by pairofcrocs**
Updated screenshots, and welcome banner.

### CODE REVIEW

**Comment by bbilly1** [comment]
very cool the mockup! That's what you get when you have professionals doing this! :-)

I was thinking, if you could add a search page screenshot too to showcase.md? As a central feature of this project, would be nice if you can see it right there with what you can do.

Maybe at the bottom of showcase the login page? That will be the first thing people see when they install the project, so they have already seen what to expect in the screenshots.

**Comment by bbilly1** [comment]
ah, and maybe keep [tube-archivist-banner.jpg](https://github.com/tubearchivist/tubearchivist/blob/master/assets/tube-archivist-banner.jpg) in the repo there, who knows, maybe somebody wants to use that for their dashboard or something...

**Comment by pairofcrocs** [comment]
[tube-archivist-social-preview.jpg](https://github.com/tubearchivist/tubearchivist/blob/master/assets/tube-archivist-social-preview.jpg) exists. I just thought it was a bit redundant to have both.

**Comment by bbilly1** [comment]
yeah, good point. Folks can crop that if need be...

**Pull request closed without merging**
