### PR TITLE
add keyboard shortcuts to video player

### PR DESCRIPTION
**Pull request by bakkot**
Fixes https://github.com/tubearchivist/tubearchivist/issues/341.

Specifically, this adds:
- 'c' to toggle captions
- 'm' to toggle mute
- '>'/'<' to increase/decrease speed (by units of .25, up to 3x)
- left-arrow/right-arrow to skip around by 5 seconds
- space to toggle play/pause even if the video element isn't selected
- '?' to show shortcuts

### CODE REVIEW

**Comment by bbilly1** [comment]
Excellent, thanks for getting this up and running so fast. I think you implemented all the most useful shortcuts! 

Looking at this: https://support.google.com/youtube/answer/7631406?hl=en, I think having `.` and `,` could also be a good addition, you know, to find these easter eggs that you see flickering by sometimes? :-) What do you think?

**Comment by bakkot** [comment]
I would've added `.` and `,`, but unfortunately I don't actually know how to advance a `video` element by a single frame, at least not without knowing the frame rate of the underlying video.

**Comment by bbilly1** [comment]
So good, you even get a little notification box with what you have just clicked, amazing! :-)

Can we apply the same for the inplace player? You know when you click on the video thumbnail it opens the player right there. I think this needs also needs the modal wrapper? Then all the templates with playable videos, has a `player-wrapper` div where the player will go like here for example: https://github.com/tubearchivist/tubearchivist/blob/master/tubearchivist/home/templates/home/home.html#L92.

Then the `createPlayer` function builds the player here: https://github.com/tubearchivist/tubearchivist/blob/master/tubearchivist/static/script.js#L348.

**Comment by bakkot** [comment]
> Can we apply the same for the inplace player?

Good catch, done.

**Comment by bbilly1** [comment]
Thanks a lot for implementing that, that's an excellent addition!

**Pull request merged**
