### PR TITLE
Add `allowed_null_keys` and its dictionary for manual imports.

### PR DESCRIPTION
**Pull request by lamusmaser**
Create default dictionary for allowed null inputs within manual imports. Related to https://github.com/tubearchivist/tubearchivist/issues/581.

### CODE REVIEW

**Comment by lamusmaser** [comment]
Sorry for the linter abuse, my local linter didn't complain about any of those issues.

**Comment by bbilly1** [comment]
Thanks for looking into this. It would be better to implement that in `_process_youtube_meta` of the `YoutubeVideo` index class. So we can keep the expected datatype and not just set it to `None`. Current behavior of yt-dlp for example is, if there aren't any tags in a video, it will be an empty list `[]`. So it would be best to imitate the same behavior too. So this could look like this:
```python
self.json_data = {
    "title": self.youtube_meta["title"],
    "description": self.youtube_meta["description"],
    "category": self.youtube_meta.get("categories", []),
    "vid_thumb_url": self.youtube_meta["thumbnail"],
    "vid_thumb_base64": base64_blur,
    "tags": self.youtube_meta.get("tags", []),
    "published": published,
    "vid_last_refresh": last_refresh,
    "date_downloaded": last_refresh,
    "youtube_id": self.youtube_id,
    # Using .value to make json encodable
    "vid_type": self.video_type.value,
    "active": True,
}
```
Note the use of `.get()` with the fallback value. then same in `_add_stats` to use `0` for `view_count` fallback.

**Comment by lamusmaser** [comment]
That's fair, I didn't want to change the base processor in `_process_youtube_meta` so that it could be untouched for YouTube interactions, but maybe that is a good fallback anyway. I can adjust the changes to be there instead of their current location.

**Comment by bbilly1** [comment]
thanks for implementing that.

**Pull request merged**
