### PR TITLE
DELETE ME - Feature #623 channel audio mode

### PR DESCRIPTION
**Pull request by greg321321**
Issue #623 

Works ok with AntennaPod and PodcastAddict Android apps. 

Ready for review.

### CODE REVIEW

**Comment by bbilly1** [comment]
OK, sorry I'm a bit slow at the moment. Plan is:
- Finish #620 and merge that
- Then finish and merge the scheduler modifications (around 90% completed now) here https://github.com/tubearchivist/tubearchivist/tree/feature-beat-model
- Then look at this

Thanks for your patience.

**Comment by Boo1098** [comment]
Haven't gotten a chance to find why, but when running your branch I found that I could get the .rss file to download after removing the auth/token from the url. This was in a new private browser window so it appears it is not checking for a token at all. When I left the auth/token in the url, I got a 502 error with no logs indicating why.

**Comment by greg321321** [comment]
> Haven't gotten a chance to find why, but when running your branch I found that I could get the .rss file to download after removing the auth/token from the url. This was in a new private browser window so it appears it is not checking for a token at all. When I left the auth/token in the url, I got a 502 error with no logs indicating why.

will look at it.

**Comment by bbilly1** [comment]
Thanks for your patience. I've made good progress with the scheduler migration. Please rebase upstream testing branch, then we can look into this next.

**Comment by greg321321** [comment]
ok, there is one additonal fix I will put in regarding a safeguard against too many requests to content interface. AirPod app requests 100 video files at a time if that is what is in it's download queue. This makes TA slow and unable to respond to all requests, including user requests on the TA UI.

**Comment by greg321321** [comment]
ok sounds good. I have time this weekend to issue updated pull request.

**Comment by greg321321** [comment]
synced changes with testing branch, but "Files changed" tab doesn't show the latest testing branch changes. Should I delete this pull request and re-issue it?

**Comment by bbilly1** [comment]
Yes, feel free to reopen.

You'll have to merge testing branch into your branch and resolve the conflicts.

**Comment by greg321321** [comment]
I am issuing a new pull request for this feature. delete this pull request.

**Pull request closed without merging**
